version: "3.8"
 
services:
  database:
    image: 'mariadb:10.4.34'
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'true'
    volumes:
      - './database:/var/lib/mysql'
  
  backend:
    image: 'filippobosi/meal-project-backend:v0.1'
    depends_on:
      - database
    ports:
      - 3000:3000
